spring.application.name=MagicFridgeAI
#server.port=8081

# Configurando o banco de dados
spring.h2.console.enabled=false
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/magicfridge}
spring.datasource.username=${DATABASE_USERNAME:magicfridge}
spring.datasource.password=${DATABASE_PASSWORD:magicfridge}

# Configuracao do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configurar o Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

chatgpt.api.url=https://api.openai.com/v1/responses
chatgpt.api.key=${API_KEY:}
