ALTER TABLE Food_item ADD COLUMN unidade VARCHAR(20) NOT NULL DEFAULT 'UNIDADE';
ALTER TABLE Food_item ALTER COLUMN categoria TYPE VARCHAR(40);
ALTER TABLE Food_item ALTER COLUMN categoria DROP NOT NULL;
